name: Full CI/CD Demo (Test & Plot)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  ci-checks:
    name: Lint & Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          
      - name: Test with pytest
        run: |
          pytest
          

  cd-run-plot:
    name: Generate & Deploy Plot
    runs-on: ubuntu-latest
    
    needs: ci-checks
    

    if: github.event_name != 'pull_request'
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run plot generation script
        run: |
          python models_comparison.py

      - name: Upload Plot Artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-comparison-plot
          path: output/comparison_plot.png
          retention-days: 5
